version: '3'

services:
  spare-parts-recognition:
    container_name: spare-parts-recognition
    image: cyranochen/spare-parts-recognition:latest
    ports:
      - "8005:8000"
      - "9005:8443"
      - "8085:8080"
      - "9085:8090"
    volumes:
      - ./server/logs:/home/server/logs
      - ./server/sample:/home/server/sample
      - ./server/label:/home/server/label
      - ./server/config.py:/home/server/config.py
      - ./client/package.json:/home/client/package.json #dev
      - ./client/pages:/home/client/pages # dev
      - ./client/dist:/home/client/dist #dev
      - ./client/index.js:/home/client/index.js #dev
    command: sh start.sh
