version: '3'

services:
  spare-parts-recognition:
    container_name: spare-parts-recognition
    image: cyranochen/spare-parts-recognition:latest
    ports:
      - "8005:8000"
      - "8085:8080"
    volumes:
      - ./server/log:/code/log
      - ./server/sample:/code/sample
      - ./server/label:/code/label
      - ./server/config.py:/code/config.py
      - ./client/package.json:/home/client/package.json #dev
      - ./client/pages:/home/client/pages # dev
      - ./client/dist:/home/client/dist #dev
      - ./client/index.js:/home/client/index.js #dev
    command: sh start.sh
