version: '3'

services:
  spare-parts-recognition:
    container_name: spare-parts-recognition
    image: cyranochen/spare-parts-recognition:latest
    ports:
      - "8005:8000"
      - "9005:9000"
      - "8085:8080"
      - "9085:9080"
    volumes:
      - ./server/logs:/home/server/logs
      - ./server/sample:/home/server/sample
      - ./server/label:/home/server/label
      - ./server/config.py:/home/server/config.py
      - ./server/:/home/server # dev
      - ./client/app:/home/client/app #dev
      - ./client/public:/home/client/public # dev
      - ./client/index.js:/home/client/index.js #dev
      - ./client/package.json:/home/client/package.json #dev
      - ./client/logs:/home/client/logs
      - ./client/config.json:/home/client/config.json
      - ./client/app/label:/home/client/app/label
      - ./client/app/sample:/home/client/app/sample

    command: sh start.sh
