version: "3"

services:
  client:
    container_name: spare-parts-recognition-client
    image: cyranochen/spare-parts-recognition-client:latest
    ports:
      - "8000:8080"
    # volumes:
    #   - ../client/app:/app/app
    #   - ../client/.env:/app/.env
    #   - ../client/index.js:/app/index.js
    #   - ../client/test.js:/app/test.js
    depends_on:
      - server
    networks:
      - network_spr
    # entrypoint: tail -F anything

  server:
    container_name: spare-parts-recognition-server
    image: cyranochen/spare-parts-recognition-server:latest
    ports:
      - "8080:8080"
    # volumes:
    #   - ../server:/app
    networks:
      - network_spr
    # entrypoint: tail -F anything

networks:
  network_spr:
    driver: bridge
